In [1]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data/raw/fuelhh")

files = sorted(data_dir.glob("fuelhh_*.csv"))

print("Files found:")
for file in files:
    print("-", file.name)

print(f"\nNumber of yearly files: {len(files)}")

Files found:
- fuelhh_2020.csv
- fuelhh_2025.csv

Number of yearly files: 2

In [1]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data/raw/fuelhh")

files = sorted(data_dir.glob("fuelhh_*.csv"))

print(f"Number of yearly files: {len(files)}")

for file in files:
    print(f"- {file.name}")

Number of yearly files: 6
- fuelhh_2020.csv
- fuelhh_2021.csv
- fuelhh_2022.csv
- fuelhh_2023.csv
- fuelhh_2024.csv
- fuelhh_2025.csv

In [2]:
summary = []

for file in files:
    df_year = pd.read_csv(file)

    summary.append({
        "year": file.stem.replace("fuelhh_", ""),
        "rows": len(df_year),
        "min_date": df_year["settlementDate"].min(),
        "max_date": df_year["settlementDate"].max(),
        "settlement_periods": df_year["settlementPeriod"].nunique(),
        "fuel_categories": df_year["fuelType"].nunique(),
        "duplicates": df_year.duplicated(
            subset=[
                "settlementDate",
                "settlementPeriod",
                "fuelType"
            ]
        ).sum(),
        "missing_values": df_year.isna().sum().sum(),
    })

summary_df = pd.DataFrame(summary)

summary_df

,year,rows,min_date,max_date,settlement_periods,fuel_categories,duplicates,missing_values
0,2020,1903057,2020-01-01,2025-12-31,50,21,257,0
1,2021,301526,2021-01-01,2021-12-31,50,19,189,0
2,2022,315072,2022-01-01,2022-12-31,50,18,36,0
3,2023,317231,2023-01-01,2023-12-31,50,19,0,0
4,2024,340894,2024-01-01,2024-12-31,50,20,0,0
5,2025,350400,2025-01-01,2025-12-31,50,20,0,0

In [3]:
total_records = summary_df["rows"].sum()

print(f"Total raw records: {total_records:,}")

Total raw records: 3,528,180

In [4]:
print(
    "Overall date range:",
    summary_df["min_date"].min(),
    "to",
    summary_df["max_date"].max()
)

Overall date range: 2020-01-01 to 2025-12-31

In [5]:
print("Years with duplicates:")
print(
    summary_df.loc[
        summary_df["duplicates"] > 0,
        ["year", "duplicates"]
    ]
)

print("\nYears with missing values:")
print(
    summary_df.loc[
        summary_df["missing_values"] > 0,
        ["year", "missing_values"]
    ]
)

Years with duplicates:
   year  duplicates
0  2020         257
1  2021         189
2  2022          36

Years with missing values:
Empty DataFrame
Columns: [year, missing_values]
Index: []

In [6]:
summary_df[
    [
        "year",
        "rows",
        "settlement_periods",
        "fuel_categories",
        "duplicates",
        "missing_values",
    ]
]

,year,rows,settlement_periods,fuel_categories,duplicates,missing_values
0,2020,1903057,50,21,257,0
1,2021,301526,50,19,189,0
2,2022,315072,50,18,36,0
3,2023,317231,50,19,0,0
4,2024,340894,50,20,0,0
5,2025,350400,50,20,0,0

In [7]:
summary_df[
    [
        "year",
        "rows",
        "settlement_periods",
        "fuel_categories",
        "duplicates",
        "missing_values",
    ]
]

,year,rows,settlement_periods,fuel_categories,duplicates,missing_values
0,2020,1903057,50,21,257,0
1,2021,301526,50,19,189,0
2,2022,315072,50,18,36,0
3,2023,317231,50,19,0,0
4,2024,340894,50,20,0,0
5,2025,350400,50,20,0,0

In [1]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data/raw/fuelhh")
files = sorted(data_dir.glob("fuelhh_*.csv"))

summary = []

for file in files:
    df_year = pd.read_csv(file)

    summary.append({
        "year": file.stem.replace("fuelhh_", ""),
        "rows": len(df_year),
        "min_date": df_year["settlementDate"].min(),
        "max_date": df_year["settlementDate"].max(),
        "settlement_periods": df_year["settlementPeriod"].nunique(),
        "fuel_categories": df_year["fuelType"].nunique(),
        "duplicates": df_year.duplicated(
            subset=[
                "settlementDate",
                "settlementPeriod",
                "fuelType"
            ]
        ).sum(),
        "missing_values": df_year.isna().sum().sum(),
    })

summary_df = pd.DataFrame(summary)

summary_df

,year,rows,min_date,max_date,settlement_periods,fuel_categories,duplicates,missing_values
0,2020,277934,2020-01-01,2020-12-31,50,16,32,0
1,2021,301526,2021-01-01,2021-12-31,50,19,189,0
2,2022,315072,2022-01-01,2022-12-31,50,18,36,0
3,2023,317231,2023-01-01,2023-12-31,50,19,0,0
4,2024,340894,2024-01-01,2024-12-31,50,20,0,0
5,2025,350400,2025-01-01,2025-12-31,50,20,0,0

In [2]:
total_records = summary_df["rows"].sum()

print(f"Total raw records: {total_records:,}")

Total raw records: 1,903,057

In [3]:
# Check settlement-period counts for every date across all years

period_check = []

for file in files:
    df_year = pd.read_csv(file)

    periods_per_day = (
        df_year.groupby("settlementDate")["settlementPeriod"]
        .nunique()
    )

    period_check.append(
        periods_per_day.rename(file.stem)
    )

period_check_df = pd.concat(period_check, axis=1)

print("Settlement periods per day:")
print(period_check_df.stack().value_counts().sort_index())

Settlement periods per day:
44.0       3
45.0       2
46.0       9
47.0      35
48.0    2137
49.0       2
50.0       4
Name: count, dtype: int64

In [4]:
for file in files:
    df_year = pd.read_csv(file)

    duplicates = df_year[
        df_year.duplicated(
            subset=[
                "settlementDate",
                "settlementPeriod",
                "fuelType"
            ],
            keep=False
        )
    ].sort_values(
        [
            "settlementDate",
            "settlementPeriod",
            "fuelType"
        ]
    )

    if not duplicates.empty:
        print(f"\n{file.name}")
        print(f"Duplicate rows: {len(duplicates):,}")
        print(duplicates.head(10).to_string(index=False))

fuelhh_2020.csv
Duplicate rows: 64
dataset          publishTime            startTime settlementDate  settlementPeriod fuelType  generation
 FUELHH 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z     2020-03-30                46  BIOMASS        2475
 FUELHH 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z     2020-03-30                46  BIOMASS        1143
 FUELHH 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z     2020-03-30                46     CCGT       10272
 FUELHH 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z     2020-03-30                46     CCGT        6864
 FUELHH 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z     2020-03-30                46     COAL         639
 FUELHH 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z     2020-03-30                46     COAL         328
 FUELHH 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z     2020-03-30                46    INTEW         -72
 FUELHH 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z     2020-03-30                46    INTEW        -226
 FUELHH 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z     2020-03-30                46    INTFR        1804
 FUELHH 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z     2020-03-30                46    INTFR        1608

fuelhh_2021.csv
Duplicate rows: 378
dataset          publishTime            startTime settlementDate  settlementPeriod fuelType  generation
 FUELHH 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z     2021-02-15                48  BIOMASS        2801
 FUELHH 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z     2021-02-15                48  BIOMASS        2283
 FUELHH 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z     2021-02-15                48     CCGT        5223
 FUELHH 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z     2021-02-15                48     CCGT        4263
 FUELHH 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z     2021-02-15                48     COAL         842
 FUELHH 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z     2021-02-15                48     COAL         713
 FUELHH 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z     2021-02-15                48    INTEW         504
 FUELHH 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z     2021-02-15                48    INTEW          70
 FUELHH 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z     2021-02-15                48    INTFR        -360
 FUELHH 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z     2021-02-15                48    INTFR        1202

fuelhh_2022.csv
Duplicate rows: 72
dataset          publishTime            startTime settlementDate  settlementPeriod fuelType  generation
 FUELHH 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z     2022-03-28                46  BIOMASS        2090
 FUELHH 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z     2022-03-28                46  BIOMASS         950
 FUELHH 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z     2022-03-28                46     CCGT       18141
 FUELHH 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z     2022-03-28                46     CCGT       14937
 FUELHH 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z     2022-03-28                46     COAL         311
 FUELHH 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z     2022-03-28                46     COAL           0
 FUELHH 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z     2022-03-28                46  INTELEC           0
 FUELHH 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z     2022-03-28                46  INTELEC           0
 FUELHH 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z     2022-03-28                46    INTEW           0
 FUELHH 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z     2022-03-28                46    INTEW           0

In [5]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data/raw/fuelhh")
files = sorted(data_dir.glob("fuelhh_*.csv"))

key_columns = [
    "settlementDate",
    "settlementPeriod",
    "fuelType"
]

for file in files:
    df_year = pd.read_csv(file)

    duplicates = (
        df_year[
            df_year.duplicated(
                subset=key_columns,
                keep=False
            )
        ]
        .sort_values(
            key_columns + ["startTime", "publishTime"]
        )
    )

    if not duplicates.empty:
        print("=" * 80)
        print(file.name)
        print(f"Duplicate rows: {len(duplicates):,}")
        print(
            f"Duplicate groups: "
            f"{duplicates.groupby(key_columns).ngroups:,}"
        )
        print()

        print(
            duplicates[
                key_columns
                + ["publishTime", "startTime", "generation"]
            ]
            .head(20)
            .to_string(index=False)
        )

================================================================================
fuelhh_2020.csv
Duplicate rows: 64
Duplicate groups: 32

settlementDate  settlementPeriod fuelType          publishTime            startTime  generation
    2020-03-30                46  BIOMASS 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z        1143
    2020-03-30                46  BIOMASS 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z        2475
    2020-03-30                46     CCGT 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z        6864
    2020-03-30                46     CCGT 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z       10272
    2020-03-30                46     COAL 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z         328
    2020-03-30                46     COAL 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z         639
    2020-03-30                46    INTEW 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z        -226
    2020-03-30                46    INTEW 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z         -72
    2020-03-30                46    INTFR 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z        1608
    2020-03-30                46    INTFR 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z        1804
    2020-03-30                46  INTIFA2 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z           0
    2020-03-30                46  INTIFA2 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z           0
    2020-03-30                46   INTIRL 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z         -46
    2020-03-30                46   INTIRL 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z         122
    2020-03-30                46   INTNED 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z         800
    2020-03-30                46   INTNED 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z         884
    2020-03-30                46   INTNEM 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z         750
    2020-03-30                46   INTNEM 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z         860
    2020-03-30                46   NPSHYD 2020-03-29T23:00:00Z 2020-03-29T22:30:00Z         454
    2020-03-30                46   NPSHYD 2020-03-30T22:00:00Z 2020-03-30T21:30:00Z         611
================================================================================
fuelhh_2021.csv
Duplicate rows: 378
Duplicate groups: 189

settlementDate  settlementPeriod fuelType          publishTime            startTime  generation
    2021-02-15                48  BIOMASS 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z        2283
    2021-02-15                48  BIOMASS 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z        2801
    2021-02-15                48     CCGT 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z        4263
    2021-02-15                48     CCGT 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z        5223
    2021-02-15                48     COAL 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z         713
    2021-02-15                48     COAL 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z         842
    2021-02-15                48    INTEW 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z          70
    2021-02-15                48    INTEW 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z         504
    2021-02-15                48    INTFR 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z        1202
    2021-02-15                48    INTFR 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z        -360
    2021-02-15                48  INTIFA2 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z         258
    2021-02-15                48  INTIFA2 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z         -28
    2021-02-15                48   INTIRL 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z         228
    2021-02-15                48   INTIRL 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z         252
    2021-02-15                48   INTNED 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z         694
    2021-02-15                48   INTNED 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z         620
    2021-02-15                48   INTNEM 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z         686
    2021-02-15                48   INTNEM 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z         790
    2021-02-15                48   INTNSL 2021-02-15T00:00:00Z 2021-02-14T23:30:00Z           0
    2021-02-15                48   INTNSL 2021-02-16T00:00:00Z 2021-02-15T23:30:00Z           0
================================================================================
fuelhh_2022.csv
Duplicate rows: 72
Duplicate groups: 36

settlementDate  settlementPeriod fuelType          publishTime            startTime  generation
    2022-03-28                46  BIOMASS 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z         950
    2022-03-28                46  BIOMASS 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z        2090
    2022-03-28                46     CCGT 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z       14937
    2022-03-28                46     CCGT 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z       18141
    2022-03-28                46     COAL 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z           0
    2022-03-28                46     COAL 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z         311
    2022-03-28                46  INTELEC 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z           0
    2022-03-28                46  INTELEC 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z           0
    2022-03-28                46    INTEW 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z           0
    2022-03-28                46    INTEW 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z           0
    2022-03-28                46    INTFR 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z        -390
    2022-03-28                46    INTFR 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z        -252
    2022-03-28                46  INTIFA2 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z         -70
    2022-03-28                46  INTIFA2 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z        -634
    2022-03-28                46   INTIRL 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z         -82
    2022-03-28                46   INTIRL 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z        -330
    2022-03-28                46   INTNED 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z         904
    2022-03-28                46   INTNED 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z         796
    2022-03-28                46   INTNEM 2022-03-27T23:00:00Z 2022-03-27T22:30:00Z         542
    2022-03-28                46   INTNEM 2022-03-28T22:00:00Z 2022-03-28T21:30:00Z         740

In [6]:
for file in files:
    df_year = pd.read_csv(file)

    exact_duplicates = df_year.duplicated(
        keep=False
    ).sum()

    print(
        f"{file.name}: "
        f"{exact_duplicates:,} exact duplicate rows"
    )

fuelhh_2020.csv: 0 exact duplicate rows
fuelhh_2021.csv: 0 exact duplicate rows
fuelhh_2022.csv: 0 exact duplicate rows
fuelhh_2023.csv: 0 exact duplicate rows
fuelhh_2024.csv: 0 exact duplicate rows
fuelhh_2025.csv: 0 exact duplicate rows

In [7]:
for file in files:
    df_year = pd.read_csv(file)

    periods_per_day = (
        df_year
        .groupby("settlementDate")["settlementPeriod"]
        .nunique()
    )

    incomplete = periods_per_day[
        ~periods_per_day.isin([46, 48, 50])
    ]

    if not incomplete.empty:
        print("=" * 80)
        print(file.name)
        print("Dates with unexpected settlement-period counts:")
        print(incomplete.to_string())

================================================================================
fuelhh_2020.csv
Dates with unexpected settlement-period counts:
settlementDate
2020-03-30    47
2020-04-30    45
2020-08-06    44
2020-10-25    49
2020-11-19    44
================================================================================
fuelhh_2021.csv
Dates with unexpected settlement-period counts:
settlementDate
2021-02-18    47
2021-02-20    47
2021-02-27    47
2021-03-29    47
2021-04-29    47
2021-06-16    47
2021-07-22    47
2021-08-29    47
2021-09-21    47
2021-09-29    47
2021-10-10    47
2021-10-13    47
2021-10-16    47
2021-10-31    49
2021-11-23    44
2021-12-03    47
2021-12-06    47
2021-12-08    47
2021-12-15    47
2021-12-23    47
2021-12-30    47
================================================================================
fuelhh_2022.csv
Dates with unexpected settlement-period counts:
settlementDate
2022-01-02    47
2022-01-10    47
2022-01-18    45
2022-01-20    47
2022-02-06    47
2022-02-10    47
2022-02-12    47
2022-02-17    47
2022-03-03    47
2022-03-07    47
2022-03-28    47
2022-04-30    47
2022-07-09    47
2022-09-23    47
================================================================================
fuelhh_2023.csv
Dates with unexpected settlement-period counts:
settlementDate
2023-07-17    47
2023-12-29    47

In [8]:
for file in files:
    df_year = pd.read_csv(file)

    periods_per_day = (
        df_year
        .groupby("settlementDate")["settlementPeriod"]
        .nunique()
    )

    incomplete_dates = periods_per_day[
        ~periods_per_day.isin([46, 48, 50])
    ].index

    if len(incomplete_dates) > 0:
        example_date = incomplete_dates[0]

        print("=" * 80)
        print(f"{file.name} - example date: {example_date}")

        example = df_year[
            df_year["settlementDate"] == example_date
        ]

        print(
            "Settlement periods present:"
        )
        print(
            sorted(
                example["settlementPeriod"].unique()
            )
        )

        print(
            f"Rows returned: {len(example):,}"
        )
    else:
        print(f"{file.name}: no incomplete dates")

================================================================================
fuelhh_2020.csv - example date: 2020-03-30
Settlement periods present:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47)]
Rows returned: 768
================================================================================
fuelhh_2021.csv - example date: 2021-02-18
Settlement periods present:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47)]
Rows returned: 799
================================================================================
fuelhh_2022.csv - example date: 2022-01-02
Settlement periods present:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(45), np.int64(46), np.int64(47), np.int64(48)]
Rows returned: 846
================================================================================
fuelhh_2023.csv - example date: 2023-07-17
Settlement periods present:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(46), np.int64(47), np.int64(48)]
Rows returned: 846
fuelhh_2024.csv: no incomplete dates
fuelhh_2025.csv: no incomplete dates

In [9]:
for file in files:
    df_year = pd.read_csv(file)

    df_year["publishTime"] = pd.to_datetime(
        df_year["publishTime"],
        utc=True
    )

    df_year["startTime"] = pd.to_datetime(
        df_year["startTime"],
        utc=True
    )

    # Check whether startTime + fuelType is unique
    duplicate_start = df_year.duplicated(
        subset=["startTime", "fuelType"],
        keep=False
    )

    print("=" * 80)
    print(file.name)
    print(
        "Duplicate startTime + fuelType rows:",
        duplicate_start.sum()
    )

================================================================================
fuelhh_2020.csv
Duplicate startTime + fuelType rows: 0
================================================================================
fuelhh_2021.csv
Duplicate startTime + fuelType rows: 0
================================================================================
fuelhh_2022.csv
Duplicate startTime + fuelType rows: 0
================================================================================
fuelhh_2023.csv
Duplicate startTime + fuelType rows: 0
================================================================================
fuelhh_2024.csv
Duplicate startTime + fuelType rows: 0
================================================================================
fuelhh_2025.csv
Duplicate startTime + fuelType rows: 0

In [10]:
for file in files:
    df_year = pd.read_csv(file)

    df_year["publishTime"] = pd.to_datetime(
        df_year["publishTime"],
        utc=True
    )

    df_year["startTime"] = pd.to_datetime(
        df_year["startTime"],
        utc=True
    )

    # Sort so the newest publication is first
    df_latest = (
        df_year
        .sort_values("publishTime")
        .drop_duplicates(
            subset=["startTime", "fuelType"],
            keep="last"
        )
    )

    remaining_duplicates = df_latest.duplicated(
        subset=["startTime", "fuelType"]
    ).sum()

    print(
        f"{file.name}: "
        f"{len(df_year):,} raw rows → "
        f"{len(df_latest):,} canonical rows | "
        f"remaining duplicates: "
        f"{remaining_duplicates:,}"
    )

fuelhh_2020.csv: 277,934 raw rows → 277,934 canonical rows | remaining duplicates: 0
fuelhh_2021.csv: 301,526 raw rows → 301,526 canonical rows | remaining duplicates: 0
fuelhh_2022.csv: 315,072 raw rows → 315,072 canonical rows | remaining duplicates: 0
fuelhh_2023.csv: 317,231 raw rows → 317,231 canonical rows | remaining duplicates: 0
fuelhh_2024.csv: 340,894 raw rows → 340,894 canonical rows | remaining duplicates: 0
fuelhh_2025.csv: 350,400 raw rows → 350,400 canonical rows | remaining duplicates: 0

In [11]:
for file in files:
    df_year = pd.read_csv(file)

    df_year["publishTime"] = pd.to_datetime(
        df_year["publishTime"],
        utc=True
    )

    df_year["startTime"] = pd.to_datetime(
        df_year["startTime"],
        utc=True
    )

    df_latest = (
        df_year
        .sort_values("publishTime")
        .drop_duplicates(
            subset=["startTime", "fuelType"],
            keep="last"
        )
    )

    periods_per_day = (
        df_latest
        .groupby("settlementDate")["settlementPeriod"]
        .nunique()
    )

    unexpected = periods_per_day[
        ~periods_per_day.isin([46, 48, 50])
    ]

    print("=" * 80)
    print(file.name)

    if unexpected.empty:
        print("No unexpected settlement-period counts.")
    else:
        print(unexpected.to_string())

================================================================================
fuelhh_2020.csv
settlementDate
2020-03-30    47
2020-04-30    45
2020-08-06    44
2020-10-25    49
2020-11-19    44
================================================================================
fuelhh_2021.csv
settlementDate
2021-02-18    47
2021-02-20    47
2021-02-27    47
2021-03-29    47
2021-04-29    47
2021-06-16    47
2021-07-22    47
2021-08-29    47
2021-09-21    47
2021-09-29    47
2021-10-10    47
2021-10-13    47
2021-10-16    47
2021-10-31    49
2021-11-23    44
2021-12-03    47
2021-12-06    47
2021-12-08    47
2021-12-15    47
2021-12-23    47
2021-12-30    47
================================================================================
fuelhh_2022.csv
settlementDate
2022-01-02    47
2022-01-10    47
2022-01-18    45
2022-01-20    47
2022-02-06    47
2022-02-10    47
2022-02-12    47
2022-02-17    47
2022-03-03    47
2022-03-07    47
2022-03-28    47
2022-04-30    47
2022-07-09    47
2022-09-23    47
================================================================================
fuelhh_2023.csv
settlementDate
2023-07-17    47
2023-12-29    47
================================================================================
fuelhh_2024.csv
No unexpected settlement-period counts.
================================================================================
fuelhh_2025.csv
No unexpected settlement-period counts.

In [12]:
import pandas as pd

for file in files:
    df_year = pd.read_csv(file)

    df_year["startTime"] = pd.to_datetime(
        df_year["startTime"],
        utc=True
    )

    # Number of unique half-hour timestamps
    timestamps = df_year["startTime"].nunique()

    print("=" * 70)
    print(file.name)
    print(f"Unique startTime values: {timestamps:,}")
    print(
        f"Start: {df_year['startTime'].min()}"
    )
    print(
        f"End:   {df_year['startTime'].max()}"
    )

======================================================================
fuelhh_2020.csv
Unique startTime values: 17,555
Start: 2019-12-31 23:30:00+00:00
End:   2020-12-31 23:00:00+00:00
======================================================================
fuelhh_2021.csv
Unique startTime values: 17,505
Start: 2020-12-31 23:30:00+00:00
End:   2021-12-31 23:00:00+00:00
======================================================================
fuelhh_2022.csv
Unique startTime values: 17,504
Start: 2021-12-31 23:30:00+00:00
End:   2022-12-31 23:30:00+00:00
======================================================================
fuelhh_2023.csv
Unique startTime values: 17,518
Start: 2023-01-01 00:00:00+00:00
End:   2023-12-31 23:30:00+00:00
======================================================================
fuelhh_2024.csv
Unique startTime values: 17,568
Start: 2024-01-01 00:00:00+00:00
End:   2024-12-31 23:30:00+00:00
======================================================================
fuelhh_2025.csv
Unique startTime values: 17,520
Start: 2025-01-01 00:00:00+00:00
End:   2025-12-31 23:30:00+00:00

In [13]:
for file in files:
    df_year = pd.read_csv(file)

    df_year["startTime"] = pd.to_datetime(
        df_year["startTime"],
        utc=True
    )

    timestamps = (
        df_year["startTime"]
        .drop_duplicates()
        .sort_values()
    )

    gaps = timestamps.diff().dropna()

    print("=" * 70)
    print(file.name)
    print(gaps.value_counts().head(10))

======================================================================
fuelhh_2020.csv
startTime
0 days 00:30:00    17545
0 days 01:00:00        5
0 days 01:30:00        4
Name: count, dtype: int64
======================================================================
fuelhh_2021.csv
startTime
0 days 00:30:00    17491
0 days 01:00:00       12
0 days 02:00:00        1
Name: count, dtype: int64
======================================================================
fuelhh_2022.csv
startTime
0 days 00:30:00    17488
0 days 01:00:00       14
0 days 02:00:00        1
Name: count, dtype: int64
======================================================================
fuelhh_2023.csv
startTime
0 days 00:30:00    17515
0 days 01:00:00        2
Name: count, dtype: int64
======================================================================
fuelhh_2024.csv
startTime
0 days 00:30:00    17567
Name: count, dtype: int64
======================================================================
fuelhh_2025.csv
startTime
0 days 00:30:00    17519
Name: count, dtype: int64

In [14]:
all_fuels = set()

for file in files:
    df_year = pd.read_csv(file)
    all_fuels.update(df_year["fuelType"].unique())

print(f"Total unique fuel categories across 2020-2025: {len(all_fuels)}")

for fuel in sorted(all_fuels):
    print(fuel)

Total unique fuel categories across 2020-2025: 21
BIOMASS
CCGT
COAL
INTELE
INTELEC
INTEW
INTFR
INTGRNL
INTIFA2
INTIRL
INTNED
INTNEM
INTNSL
INTVKL
NPSHYD
NUCLEAR
OCGT
OIL
OTHER
PS
WIND

In [15]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("../data/raw/fuelhh")
PROCESSED_DIR = Path("../data/processed")

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

files = sorted(RAW_DIR.glob("fuelhh_*.csv"))

dfs = []

for file in files:
    print(f"Loading {file.name}...")
    
    df_year = pd.read_csv(
        file,
        dtype={
            "dataset": "string",
            "fuelType": "string"
        }
    )
    
    dfs.append(df_year)

fuelhh = pd.concat(
    dfs,
    ignore_index=True
)

print(f"\nTotal rows: {len(fuelhh):,}")
print(f"Columns: {fuelhh.columns.tolist()}")

Loading fuelhh_2020.csv...
Loading fuelhh_2021.csv...
Loading fuelhh_2022.csv...
Loading fuelhh_2023.csv...
Loading fuelhh_2024.csv...
Loading fuelhh_2025.csv...

Total rows: 1,903,057
Columns: ['dataset', 'publishTime', 'startTime', 'settlementDate', 'settlementPeriod', 'fuelType', 'generation']

In [16]:
fuelhh["startTime"] = pd.to_datetime(
    fuelhh["startTime"],
    utc=True
)

fuelhh["publishTime"] = pd.to_datetime(
    fuelhh["publishTime"],
    utc=True
)

In [17]:
fuelhh["datetime_uk"] = (
    fuelhh["startTime"]
    .dt.tz_convert("Europe/London")
)

In [18]:
duplicate_key_count = fuelhh.duplicated(
    subset=["startTime", "fuelType"]
).sum()

print(
    f"Duplicate startTime + fuelType rows: "
    f"{duplicate_key_count:,}"
)

Duplicate startTime + fuelType rows: 0

In [19]:
fuel_profile = (
    fuelhh
    .groupby("fuelType")
    .agg(
        records=("fuelType", "size"),
        min_generation_mw=("generation", "min"),
        max_generation_mw=("generation", "max"),
        mean_generation_mw=("generation", "mean"),
    )
    .sort_index()
)

fuel_profile

          records  min_generation_mw  max_generation_mw  mean_generation_mw
fuelType
BIOMASS    105170                  0               3368         1977.439954
CCGT       105170                  0              27339        10447.920671
COAL       105170                  0               4392          341.140772
INTELE          9                  0                  0            0.000000
INTELEC     75310              -1034               1260          314.040632
INTEW      105170               -588                506          -95.569288
INTFR      105170              -2072               2630          787.154702
INTGRNL     24622               -516                506         -228.434327
INTIFA2    102224              -1626               1398          262.422288
INTIRL     105170               -592                682         -145.333897
INTNED     105170              -1092               1402          276.281715
INTNEM     105170              -1024               1366          409.393781
INTNSL      86347              -1456               1846          725.200296
INTVKL      36995              -1460               2480          338.365995
NPSHYD     105170                  0               1181          400.537473
NUCLEAR    105170                  0               6986         4679.893943
OCGT       105170                  0               1097           22.123067
OIL        105170                  0                138            0.008149
OTHER      105170                  0               3187          315.025901
PS         105170              -2480               2444          -60.907445
WIND       105170                  0              18382         6900.210764

In [20]:
sorted(fuelhh["fuelType"].dropna().unique())

['BIOMASS',
 'CCGT',
 'COAL',
 'INTELE',
 'INTELEC',
 'INTEW',
 'INTFR',
 'INTGRNL',
 'INTIFA2',
 'INTIRL',
 'INTNED',
 'INTNEM',
 'INTNSL',
 'INTVKL',
 'NPSHYD',
 'NUCLEAR',
 'OCGT',
 'OIL',
 'OTHER',
 'PS',
 'WIND']

In [21]:
timestamps = (
    fuelhh["startTime"]
    .drop_duplicates()
    .sort_values()
)

gaps = timestamps.diff().dropna()

gap_summary = (
    gaps
    .value_counts()
    .sort_index()
)

gap_summary

startTime
0 days 00:30:00    105130
0 days 01:00:00        33
0 days 01:30:00         4
0 days 02:00:00         2
Name: count, dtype: int64

In [22]:
fuelhh["date"] = fuelhh["datetime_uk"].dt.date
fuelhh["hour"] = fuelhh["datetime_uk"].dt.hour
fuelhh["minute"] = fuelhh["datetime_uk"].dt.minute
fuelhh["day_of_week"] = fuelhh["datetime_uk"].dt.day_name()
fuelhh["month"] = fuelhh["datetime_uk"].dt.month
fuelhh["year"] = fuelhh["datetime_uk"].dt.year
fuelhh["is_weekend"] = (
    fuelhh["datetime_uk"].dt.dayofweek >= 5
)